const products = [
    {title: 'Adesivo Plus', path: './img/adesivo_plus.jpg'},
    {title: 'Acionador de Emergência', path: './img/acionador_emergencia.jpg'},
    {title: 'Botoeira Yale', path: './img/botoeira_yale.jpg'},
    {title: 'Adesivo Automatiza', path: './img/adesivo_automatiza.jpg'},
    {title: 'Boteira Inox Sobrepor Fina', path: './img/botoeira_inox_sobrepor_fina.jpg'},
    {title: 'Botoeira Sem Fio', path: './img/botoeira_sem_fio.jpg'},
    {title: 'Bateria Interna 3V', path: './img/bateria_interna_3v.jpg'},
    {title: 'Bala Solenoide Catraca', path: './img/bala_solenoide_catraca.jpg'},
    {title: 'Botão Plus', path: './img/botao_plus.jpg'},
    {title: 'Bateria No-Break Prisma ADV', path: './img/bateria_no-break_prisma_adv.jpg'},
    {title: 'Bucha Lateral Plus', path: './img/bucha_lateral_plus.jpg'},
    {title: 'Bateria No-Break Vega', path: './img/bateria_no-break_vega.jpg'},
    {title: 'Bateria No-Break iDClass', path: './img/bateria_no-break_idclass.jpg'},
    {title: 'Botoeira AGL', path: './img/botoeira_agl.jpg'},
    {title: 'Chave iDClass', path: './img/chave_idclass.jpg'},
    {title: 'Borne BNC', path: './img/borne_bnc.jpg'},
    {title: 'Cabo Sensor Catraca', path: './img/cabo_sensor_catraca.jpg'},
    {title: 'Cabeça Impressão Plus', path: './img/cabeca_impressao_plus.jpg'},
    {title: 'Carro Transporte Plus', path: './img/carro_transporte_plus.jpg'},
    {title: 'Caneta iDClass', path: './img/caneta_idclass.jpg'},
    {title: 'Botão Liga/Desliga Plus', path: './img/botao_liga_desliga_plus.jpg'},
    {title: 'Cabo Sensor Plus', path: './img/cabo_sensor_plus.jpg'},
    {title: 'Catraca Impressora Plus', path: './img/catraca_impressora_plus.jpg'},
    {title: 'Conector Keystone', path: './img/conector_keystone.jpg'},
    {title: 'Cartucho USB', path: './img/cartucho_usb.jpg'},
    {title: 'Display Diversos', path: './img/display_diversos.jpg'},
    {title: 'Eixo Estriado Plus', path: './img/eixo_estriado_plus.jpg'},
    {title: 'Engrenagem Intermediaria Plus', path: './img/engrenagem_intermediaria_plus.jpg'},
];